### PR TITLE
change tendrl.conf locations to node-agent.conf.yaml

### PR DESCRIPTION
**Pull request by fbalak**

### CODE REVIEW

**Comment by fbalak** [comment]
Don't merge it yet. I still want to fix something according to https://github.com/Tendrl/node-agent/blob/master/doc/source/installation.rst.

**Comment by dahorak** [comment]
OK, (otherwise installation in CI passed)

**Comment by mkudlej** [comment]
LGTM

**Comment by fbalak** [comment]
merged

**Pull request merged**
